### ISSUE TITLE
TypeError: initialize_agent() missing 1 required positional argument: 'tools'

### ISSUE THREAD

**Issue by ValenteMendez** [kyegomez/tree-of-thoughts#14]
Hi, thank you for this! Question, I keep getting this mistake, any idea of how to fix it?

(base) .../tree-of-thoughts/example.py
Traceback (most recent call last):
  File ".../tree-of-thoughts/example.py", line 13, in <module>
    model = LangchainCustomLanguageModel(api_key=api_key)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File ".../tree-of-thoughts/example.py", line 50, in __init__
    self.agent = initialize_agent(llm=model, agent=AgentType.REACT_DOCSTORE, verbose=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: initialize_agent() missing 1 required positional argument: 'tools'

**Comment by kyegomez** [comment]
I think i fixed it! Download the latest version again and try pls
