### ISSUE TITLE
def solve arguments don't match example.py solve call

### ISSUE THREAD

**Issue by jabowery** [kyegomez/tree-of-thoughts#15]
In `example.py`:
``solution = tree_of_thoughts.solve(input_problem, k, T, b, vth, timeout, confidence_threshold=confidence, max_iterations=max_iterations, convergence_threshold=convergence_threshold, convergence_count=convergence_count)``

but in `treeofthoughts.py`:

```
class TreeofThoughts
...
def solve(self, x, k, T, b, vth, timeout=None)
```

**Comment by kyegomez** [comment]
I think i fixed it! Download the latest version again and try pls

**Comment by jabowery** [comment]
With `use_v2=False` there is no execution path that sets `solution`.
