### ISSUE TITLE
Support for ChatGPT with plugins

### ISSUE THREAD

**Issue by AZm1n** [kyegomez/tree-of-thoughts#20]
Thank you for implementing the ToT paper.
 I have a question though, is there anyway where this can be used with GP-4 running on the web ChatGPT with plugins?
If not are there any roadmap or some thoughts of how to achieve this?
Thanks

**Comment by Undertone0809** [comment]
You can use it in combination with langchain.

**Comment by kyegomez** [comment]
We can make an ChatGPT plugin, would you be interested in that? And we're also trying to implement an stacked langchains agent class with tot and browser capabilities
