### ISSUE TITLE
UnboundLocalError: local variable 'prompt'

### ISSUE THREAD

**Issue by AshVR** [kyegomez/tree-of-thoughts#24]
Getting this error from the example.py 

 \tree-of-thoughts\tree_of_thoughts\treeofthoughts.py", line 144, in evaluate_states
    prompt = f"Given the current state of reasoning: '{state_text}', evaluate its value as a float between 0 and 1, on the probability of this state of reasoning achieveing {prompt} and NOTHING ELSE:"
UnboundLocalError: local variable 'prompt' referenced before assignment

**Comment by malerius** [comment]
Same for me

**Comment by kyegomez** [comment]
Try now with git clone 😊
