### ISSUE TITLE
Not initialized input handling, it's breaking down each token in the string as an input parameter (x)

### ISSUE THREAD

**Issue by kyegomez** [kyegomez/tree-of-thoughts#27]

**Comment by baldeav** [comment]
[/usr/local/lib/python3.10/dist-packages/tree_of_thoughts/treeofthoughts.py](https://localhost:8080/#) in tot_bfs(self, x, k, T, b)
    836         for t in range(1, T + 1):
    837             S0_t = {(*s, z) for s in S0 for z in self.model.generate_thoughts(s, k)}
--> 838             Vt = self.model.evaluate_states(S0_t)
    839             St = sorted(S0_t, key=lambda s: Vt[s], reverse=True)[:b]
    840             S0 = set(St)

TypeError: OpenAILanguageModel.evaluate_states() missing 1 required positional argument: 'inital_prompt'
