### ISSUE TITLE
ModuleNotFoundError: No module named 'treeofthoughts'

### ISSUE THREAD

**Issue by distbit0** [kyegomez/tree-of-thoughts#3]
```
Traceback (most recent call last):
  File "/home/pimania/Dev/AGI/treeOfThoughtsTest/exmaple.py", line 1, in <module>
    from tree_of_thoughts import (
  File "/home/pimania/.local/lib/python3.10/site-packages/tree_of_thoughts/__init__.py", line 1, in <module>
    from treeofthoughts import TreeofThoughts, CustomLanguageModel
ModuleNotFoundError: No module named 'treeofthoughts'
```

the above error is what I receive when attempting to run the code in README.md, after already having run `pip install tree-of-thoughts`

Seems that perhaps it should be importing tree-of-thoughts instead of treeofthoughts?

**Comment by kyegomez** [comment]
I didn't import in the __init__.py like this: ``` tree_of_thoughts.treeofthoughts``` but it should work now, let me know
