### ISSUE TITLE
TypeError: TreeofThoughts.solve() got an unexpected keyword argument 'T'

### ISSUE THREAD

**Issue by ivanrlg** [kyegomez/tree-of-thoughts#39]
C:\Users\ivanr\tree-of-thoughts\tree_of_thoughts>python3 treeofthoughts.py --problem "design an new transportation system for an all-new city" --search_algorithm="BFS"
Namespace(problem='design an new transportation system for an all-new city', version=1, search_algorithm='BFS', k=3, T=10, b=5, vth=0.4, timeout=10, confidence=0.8, max_iterations=40, convergence_threshold=0.01, convergence_count=5)
Using api_model text-davinci-003
Traceback (most recent call last):
  File "C:\Users\ivanr\tree-of-thoughts\tree_of_thoughts\treeofthoughts.py", line 630, in <module>
    best_state = optimized_tree_of_thoughts.solve(args.problem, k=args.k, T=args.T, b=args.b, vth=args.vth)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TreeofThoughts.solve() got an unexpected keyword argument 'k'

**Comment by wqw547243068** [comment]
One solution:

```py
    #optimized_tree_of_thoughts = TreeofThoughts(model, search_algorithm=args.search_algorithm)
    optimized_tree_of_thoughts = OptimizedTreeofThoughts(model, search_algorithm=args.search_algorithm)
```

**Comment by kyegomez** [comment]
Hey patched, please try again!
