### ISSUE TITLE
can we not use api of openai, but local vicuna instead?

### ISSUE THREAD

**Issue by 1lifetime1** [kyegomez/tree-of-thoughts#4]

**Comment by kyegomez** [comment]
Yes, of course let's make a class together, we can use the majority of the OpenAI Class but we'll have to change the api call to the weights initialization

**Comment by yhyu13** [comment]
@kyegomez probably we just go with Langchain or whatever that abstract LLMs models

**Comment by yhyu13** [comment]
A pr on this https://github.com/kyegomez/tree-of-thoughts/pull/8, it uses ooba's textgen webui as server.

**Comment by kyegomez** [comment]
@yhyu13 

Yeah Let's make an langchain class

**Comment by kyegomez** [comment]
And @1lifetime1 help build the class for vicuna!
