### ISSUE TITLE
max() arg is an empty sequence

### ISSUE THREAD

**Issue by mustache-commits** [kyegomez/tree-of-thoughts#41]
Not reaching past Step 1 with the following error:

`2023-05-29 09:11:32,869 - INFO - Step: 2, S0_t: set(), Vt: {}, St: [], S0: set()

Saving tree

2023-05-29 09:11:32,870 - INFO - Step: 3, S0_t: set(), Vt: {}, St: [], S0: set()

2023-05-29 09:11:32,870 - ERROR - Error: max() arg is an empty sequence

2023-05-29 09:11:32,870 - INFO - Saving the current tree and metrics.`

**Comment by kyegomez** [comment]
Which search algorithm are you using?

**Comment by mustache-commits** [comment]
BFS. I noticed that it depends on the problem. Simple math problems are OK, but as soon as it is slighly more elaborate it runs into problems with pruning and text cutoff. I resolved it by increasing max_tokens and adding pruning threshold management.

**Comment by kyegomez** [comment]
What do you mean by pruning threshold management?
