### ISSUE TITLE
ModuleNotFoundError: No module named 'tree_of_thoughts'

### ISSUE THREAD

**Issue by douglasdew** [kyegomez/tree-of-thoughts#43]
I encounter that error when attempting to follow the instructions in the README.

cd tree-of-thoughts
python3 -m pip install -r requirements.txt
cd tree_of_thoughts
python3 treeofthoughts.py --problem "design an new transportation system for an all-new city" --search_algorithm="BFS"

**Comment by kyegomez** [comment]
Hey did you pip install? Or both? There are 2 methods, pip install or git clone

**Comment by douglasdew** [comment]
I used git clone. I was able to clear the error by modifying all of the import statements so that they did not reference the tree_of_thoughts module.

**Comment by douglasdew** [comment]
Thank you for sharing your code. I'm working now to get a complete example running. The treeofthoughts.py file seems to have only the first part of a working example, as many lines of code are commented out.

**Comment by danmarshall** [comment]
@douglasdew I had the same issue, can you send your fixes in a PR? I'm also using the git clone.
