### ISSUE TITLE
Problems installing in Google Colab

### ISSUE THREAD

**Issue by Adportas** [kyegomez/tree-of-thoughts#45]
Cloned the repo to my Google Drive ad did some mods to thee code to run in Google Colab:

%cd /content/drive/MyDrive/tree-of-thoughts/
!python3 -m pip install -r requirements.txt
%cd tree_of_thoughts
!python3 treeofthoughts.py --problem "design an new transportation system for an all-new city" --search_algorithm="BFS"

Got this error:

/content/drive/MyDrive/tree-of-thoughts
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 1)) (4.29.2)
Requirement already satisfied: openai in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 2)) (0.27.7)
Requirement already satisfied: guidance in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 3)) (0.0.57)
Collecting dotenv (from -r requirements.txt (line 4))
  Using cached dotenv-0.0.5.tar.gz (2.4 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
/content/drive/MyDrive/tree-of-thoughts/tree_of_thoughts
Traceback (most recent call last):
  File "/content/drive/MyDrive/tree-of-thoughts/tree_of_thoughts/treeofthoughts.py", line 6, in <module>
    from tree_of_thoughts.openaiModels import OptimizedOpenAILanguageModel
ModuleNotFoundError: No module named 'tree_of_thoughts'

**Comment by kyegomez** [comment]
Just fixed it! Try again please !
