### ISSUE TITLE
Mismatch in number of arguments for TreeofThoughts.tot_bfs()

### ISSUE THREAD

**Issue by lbrichards** [kyegomez/tree-of-thoughts#48]
Inside `solve()` `tot_bfs()` is called with args 

```initial_prompt, num_thoughts, max_steps, max_states, value_threshold, pruning_threshold```

but in the method definition `value_threshold` does not appear.  This mismatch causes a crash when running example.

**Comment by kyegomez** [comment]
Hey 👋 try now please it should be fixed

**Comment by lbrichards** [comment]
Thanks!
