### ISSUE TITLE
Getting started with Method 1 & 2 

### ISSUE THREAD

**Issue by alex-coch** [kyegomez/tree-of-thoughts#49]
Hi, 

Method1 doesn't output anything:
`
python3.9 treeofthoughts.py --problem "design an new transportation system for an all-new city" --search_algorithm="BFS"
2023-05-30 15:11:40,157 - INFO - Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2023-05-30 15:11:40,157 - INFO - NumExpr defaulting to 8 threads.
`

Method2 gives the issue:
`
ModuleNotFoundError: No module named 'tree_of_thoughts.huggingModel'
`

Any ideas?

**Comment by kyegomez** [comment]
Hey try upgrading or getting the newest version and let me know what happens!

**Comment by alex-coch** [comment]
The same.

Method 1:
`
git clone https://github.com/kyegomez/tree-of-thoughts
python3.9 -m pip install -r requirements.txt
ython3.9 treeofthoughts.py --problem "design an new transportation system for an all-new city" --search_algorithm="BFS"
2023-05-31 15:17:44,787 - INFO - Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2023-05-31 15:17:44,788 - INFO - NumExpr defaulting to 8 threads.
`
it's all

Method 2:
`
python3.9 -m pip uninstall tree-of-thoughts
python3.9 -m pip install tree-of-thoughts
...
Successfully installed tree-of-thoughts-0.3.1
python3.9 main.py
  4 from tree_of_thoughts.huggingModel import HuggingLanguageModel
ModuleNotFoundError: No module named 'tree_of_thoughts.huggingModel'
`

**Comment by kyegomez** [comment]
Remove the hugging model after the dot and see if that works!
