### ISSUE TITLE
how to use my own base url for openai API?

### ISSUE THREAD

**Issue by Clearave** [kyegomez/tree-of-thoughts#5]
How to customize the base URL when calling the OpenAI API?

**Comment by yhyu13** [comment]
There is a pr on this https://github.com/kyegomez/tree-of-thoughts/pull/6

**Comment by yhyu13** [comment]
@Clearave that pr was merged, you can set by OPENAI_API_BASE="https://api.openai.com/v1" or pass that variable as api_base into model argument
