### ISSUE TITLE
ModuleNotFoundError: No module named 'experiments'

### ISSUE THREAD

**Issue by mnovil** [kyegomez/tree-of-thoughts#51]
HI! I get this error when trying to run the code:

  File ~\AppData\Local\Programs\Python\Python311\Lib\site-packages\tree_of_thoughts\__init__.py:2
    from experiments.extremely_experimental.prompting.LangChain_model import LangchainCustomLanguageModel

ModuleNotFoundError: No module named 'experiments'

**Comment by kyegomez** [comment]
Hey try upgrading or getting the newest version though your preferred verision
