### ISSUE TITLE
tot_dfs() got an unexpected keyword argument 'confidence_threshold'

### ISSUE THREAD

**Issue by claudiobottari** [kyegomez/tree-of-thoughts#52]
Getting few errors likes this, should I fix it?

tree-of-thoughts\tree_of_thoughts\treeofthoughts.py", line 45, in solve
    result = self.tot_dfs(initial_prompt, num_thoughts, max_steps, value_threshold,
TypeError: tot_dfs() got an unexpected keyword argument 'confidence_threshold'

**Comment by ivanzhovannik** [comment]
@claudiobottari I have got bunch of those, too :( Basically `self.tot_dfs` and `self.tot_bfs` have a set of different arguments and no unified wrapper around them, so I edited the [TreeofThoughts class source file](https://github.com/kyegomez/tree-of-thoughts/blob/main/tree_of_thoughts/treeofthoughts.py) in my conda environment

**Comment by kyegomez** [comment]
Yeah changed 1, can you go deeper on number 2?

**Comment by ysymyth** [comment]
Hi, I'm the first author of ToT paper. please note the official implementation to replicate paper results is https://github.com/ysymyth/tree-of-thought-llm
