### ISSUE TITLE
 cannot import name 'OpenAILanguageModel' from 'tree_of_thoughts.treeofthoughts'

### ISSUE THREAD

**Issue by NixerSo5** [kyegomez/tree-of-thoughts#53]

**Comment by kyegomez** [comment]
Did you just pip install? If so remove the tree of thoughts after the dot

**Comment by kyegomez** [comment]
Just  do ```from tree_of_thoughts import ```

**Comment by kyegomez** [comment]
Hey, I believe you did not pip install!
