### ISSUE TITLE
Answer cuts off

### ISSUE THREAD

**Issue by mnovil** [kyegomez/tree-of-thoughts#64]
Hi, I've tried several prompts but the answer always cuts off. Any idea why that would be?

I don't think it has to do with the tokens limit.. This was the last response:

['The best approach to start a consulting agency to improve the processes a financial company has is to first conduct a thorough analysis of the current processes. This analysis should include identifying areas of opportunity, potential areas of improvement, and any potential risks associated with']

**Comment by kyegomez** [comment]
Hey 👋 When did you install? And yes perhaps it's the token limit

**Comment by mnovil** [comment]
Around May 27-30
