### ISSUE TITLE
huggingfaceExamples.py errors

### ISSUE THREAD

**Issue by rkuo2000** [kyegomez/tree-of-thoughts#76]
* line 6 cause error 
fix: model_Tokenizer renamed to model_tokenizer

* line 11 cause error
'TreeofThoughts' object has no attribute 'solve'
fix:
from tree_of_thoughts.treeofthoughts import MonteCarloTreeofThoughts
tree_of_thoughts= MonteCarloTreeofThoughts(model)

* After using MonteCarloTreeofThoughts(model), 
Error generating thoughts for state:
Error: '>' not supported between instances of 'int' and 'str'

Ref.  [https://www.kaggle.com/code/rkuo2000/tree-of-thoughts](https://www.kaggle.com/code/rkuo2000/tree-of-thoughts/edit)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/tree-of-thoughts/issues/76">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/tree-of-thoughts/issues/76/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/tree-of-thoughts/issues/76/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@rkuo2000 @HU-xiaobai @alxkolm its fixed now try again please
