### ISSUE TITLE
module abstractLanguageModel not found

### ISSUE THREAD

**Issue by aibarito-ua** [kyegomez/tree-of-thoughts#79]
Hello!
I am getting ModuleNotFoundError when trying to run example.py. Do you know how can I solve it?
Error:
Traceback (most recent call last):
  File "tree_of_thoughts/example.py", line 2, in <module>
    from tree_of_thoughts.models.openai_models import OpenAILanguageModel
  File "/app/tree-of-thoughts/tree_of_thoughts/__init__.py", line 2, in <module>
    from tree_of_thoughts.treeofthoughts import TreeofThoughts, MonteCarloTreeofThoughts, TreeofThoughtsBFS, TreeofThoughtsDFS, TreeofThoughtsBEST, TreeofThoughtsASearch
  File "/app/tree-of-thoughts/tree_of_thoughts/treeofthoughts.py", line 16, in <module>
    from abstractLanguageModel import AbstractLanguageModel
ModuleNotFoundError: No module named 'abstractLanguageModel'

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/tree-of-thoughts/issues/79">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/tree-of-thoughts/issues/79/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/tree-of-thoughts/issues/79/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@aibarito-ua yes try importing like this, 

treeofthoughts.models.abstract_language_model

**Comment by thiswillbeyourgithub** [comment]
It seems this was not pushed to PyPI.

It would be nice to add to the README that we can install the latest github version using pip via ` python -m pip install git+https://github.com/kyegomez/tree-of-thoughts`

**Comment by kyegomez** [comment]
@thiswillbeyourgithub please excuse me for this error, I have pushed the updates!
