### ISSUE TITLE
AttributeError: 'HuggingLanguageModel' object has no attribute 'generate_solution'

### ISSUE THREAD

**Issue by ZSCDumin** [kyegomez/tree-of-thoughts#81]
AttributeError: 'HuggingLanguageModel' object has no attribute 'generate_solution'

where  is the function?

![image](https://github.com/kyegomez/tree-of-thoughts/assets/19670365/48670717-de1b-44db-bb0a-45826eaeb0fa)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/tree-of-thoughts/issues/81">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/tree-of-thoughts/issues/81/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/tree-of-thoughts/issues/81/pledge.svg">
</picture>
</a>

**Comment by hijkzzz** [comment]
Is there any solution?

**Comment by YongLD** [comment]
They didn't define the function at all, see in `tree_of_thoughts/huggingface_model.py`
```python
class HuggingLanguageModel:
    def __init__(
        self, model_name, model_tokenizer=None, verbose=False, *args, **kwargs
    ):
         ........

    def generate_thoughts(self, state, k, max_length=100):
           .........

        return thoughts

    def evaluate_states(self, states, initial_prompt, max_length=10):
            ..........

        return state_values
```

**Comment by kyegomez** [comment]
@ZSCDumin @hijkzzz @YongLD just pushed a massive update it should be ready to go, try again now
